version: "3"

services:
  nginx:
    build:
      context: .
      dockerfile: docker/Nginx.Dockerfile
    ports:
      - 8098:80
    volumes:
      - ./:/var/www/symfony-docker
    depends_on:
      - fpm
    links:
      - fpm
  fpm:
    build:
      context: .
      dockerfile: docker/Fpm.Dockerfile
    volumes:
      - ./:/var/www/symfony-docker
    depends_on:
      - mysql
    links:
      - mysql
  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8088:80
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: rootroot
  mysql:
    image: mysql:5.7
    ports:
      - 33061:3306
    environment:
      MYSQL_ROOT_PASSWORD: rootroot
      MYSQL_DATABASE: printify_api
    volumes:
      - ./mysql-dump/printify_api.sql:/docker-entrypoint-initdb.d/printify_api.sql
